Add doc server

diff --git a/.github/workflows/unitest.yml b/.github/workflows/unitest.yml
--- a/.github/workflows/unitest.yml
+++ b/.github/workflows/unitest.yml
@@ -24,11 +24,11 @@ jobs:
           go install github.com/AlekSi/gocov-xml@latest
           go install github.com/onsi/ginkgo/v2/ginkgo@latest
 
-#      - name: Ginkgo test unit test
-#        run: ginkgo -r --focus unit
-#
-#      - name: Ginkgo test integration test
-#        run: ginkgo -r --focus integration
+      - name: Ginkgo test unit test
+        run: ginkgo -r --focus unit
+
+      - name: Ginkgo test integration test
+        run: ginkgo -r --focus integration
 
       - name: Ginkgo test
         run: |
@@ -36,14 +36,14 @@ jobs:
           gocov convert coverage.txt > coverage.json
           gocov-xml < coverage.json > coverage.xml
 
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v3
-        if: success() || failure()
-        with:
-          report_paths: 'test-report.xml'
-
-      - name: Code Coverage Summary Report
-        uses: irongut/CodeCoverageSummary@v1.3.0
-        if: success() || failure()
-        with:
-          filename: coverage.xml
+#      - name: Publish Test Report
+#        uses: mikepenz/action-junit-report@v3
+#        if: success() || failure()
+#        with:
+#          report_paths: 'test-report.xml'
+#
+#      - name: Code Coverage Summary Report
+#        uses: irongut/CodeCoverageSummary@v1.3.0
+#        if: success() || failure()
+#        with:
+#          filename: coverage.xml
